### ISSUE TITLE
Issues with Webpack

### ISSUE THREAD

**Issue by gevera** [nodegui/svelte-nodegui#50]
Have troubles running nodegui. Any ideas why this is happening?

node -v v14.15.4
gcc version 11.0.0 
cmake version 3.19.7
GNU Make 4.3
Fedora 34

`
 npm run dev

> svelte-nodegui-starter@1.0.1 dev
> webpack --mode=development

assets by status 58.1 KiB [cached] 1 asset
asset index.js 1.57 MiB [compared for emit] (name: main) 1 related asset
runtime modules 21.9 KiB 10 modules
modules by path ./node_modules/@nodegui/ 672 KiB 214 modules
modules by path ./node_modules/postcss/lib/*.js 479 KiB 25 modules
modules by path ./node_modules/source-map/ 99.4 KiB 11 modules
modules by path ./src/ 10.8 KiB 5 modules
modules by path ./node_modules/cuid/ 2.88 KiB 4 modules
modules by path ./node_modules/webpack/hot/*.js 3.75 KiB 3 modules
modules by path ./node_modules/centra/ 4.73 KiB 3 modules
modules by path ./node_modules/chalk/ 12.1 KiB 3 modules
modules by path ./node_modules/color-convert/*.js 20.3 KiB 3 modules
modules by path ./node_modules/svelte/ 54.1 KiB
  ./node_modules/svelte/internal/index.mjs 53.9 KiB [built] [code generated]
  ./node_modules/svelte/index.mjs 212 bytes [built] [code generated]
24 modules

ERROR in ./node_modules/@nodegui/nodegui/dist/lib/utils/addon.js 3:14-65
Module not found: Error: Can't resolve '../../../build/Release/nodegui_core.node' in '/home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/dist/lib/utils'
resolve '../../../build/Release/nodegui_core.node' in '/home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/dist/lib/utils'
  using description file: /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/package.json (relative path: ./dist/lib/utils)
    using description file: /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/package.json (relative path: ./build/Release/nodegui_core.node)
      no extension
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node doesn't exist
      .ts
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node.ts doesn't exist
      .mjs
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node.mjs doesn't exist
      .js
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node.js doesn't exist
      .svelte
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node.svelte doesn't exist
      .scss
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node.scss doesn't exist
      .css
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node.css doesn't exist
      .json
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node.json doesn't exist
      as directory
        /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node doesn't exist
 @ ./node_modules/@nodegui/nodegui/dist/lib/QtGui/QApplication.js 7:32-57
 @ ./node_modules/@nodegui/nodegui/dist/index.js 22:21-56
 @ ./src/App.svelte 24:0-41 112:21-26
 @ ./src/app.ts 2:0-31 3:14-17

webpack 5.24.2 compiled with 1 error in 13901 ms
No issues found.

npm run start

> svelte-nodegui-starter@1.0.1 start
> ./livereload.sh node_modules/.bin/qode ./dist/index.js

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/qode/binaries/qode ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/qode/binaries/qode',
  path: '/home/denis/projects/svelte-nodegui-starter/node_modules/@nodegui/qode/binaries/qode',
  spawnargs: [ './dist/index.js' ]
}

`

**Comment by shirakaba** [comment]
Sounds like it’s looking for a NodeGUI file and not finding it. I’ve not experienced that. Maybe first try `npm ci` to reinstall the node_modules and try again?
