### ISSUE TITLE
Error while setting up Qode

### ISSUE THREAD

**Issue by bastinald** [nodegui/svelte-nodegui#57]
```
npm ERR! Error while setting up Qode:  Error: Error while downloading Qode v2.1.0:https://github.com/nodegui/qode/releases/download/v2.1.0/qode-darwin-arm64-v2.1.0.tar.gz. Not Found
npm ERR!     at download (/Users/bastinald/Apps/svelte-nodegui-starter/node_modules/@nodegui/qode/src/downloader.js:33:11)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR!     at async setupQode (/Users/bastinald/Apps/svelte-nodegui-starter/node_modules/@nodegui/qode/src/setup.js:19:3)
npm ERR!     at async main (/Users/bastinald/Apps/svelte-nodegui-starter/node_modules/@nodegui/qode/install.js:7:5)
```

**Comment by shirakaba** [comment]
This should be filed on the `@nodegui/qode` repo, with steps to reproduce the problem, as it’s a subdependency of Svelte NodeGUI, not a part of Svelte NodeGUI itself.
